import { Soru, Konu } from "./tyt-quiz-oyunu"

// TYT müfredatına uygun gerçek sınav formatında sorular
export const quizVerisi = {
  fizik: [
    { ad: "Fizik Bilimine Giriş", sorular: [
      { soru: "Fizik bilimi hangi temel kavramları inceler?", secenekler: ["Madde ve enerji", "Sadece canlı organizmalar", "Sadece sosyal olaylar", "Sadece sanatsal faaliyetler"], dogru: "Madde ve enerji" },
      { soru: "Fizikte temel ölçüler hangisidir?", secenekler: ["Uzunluk, kütle, zaman", "Sadece uzunluk", "Sadece kütle", "Sadece zaman"], dogru: "Uzunluk, kütle, zaman" },
      { soru: "Uzunluk ölçü birimi nedir?", secenekler: ["metre (m)", "kilogram (kg)", "saniye (s)", "litre (L)"], dogru: "metre (m)" },
      { soru: "Kütle ölçü birimi nedir?", secenekler: ["kilogram (kg)", "metre (m)", "saniye (s)", "amper (A)"], dogru: "kilogram (kg)" },
      { soru: "Zaman ölçü birimi nedir?", secenekler: ["saniye (s)", "metre (m)", "kilogram (kg)", "kelvin (K)"], dogru: "saniye (s)" },
      { soru: "1 km kaç metredir?", secenekler: ["1000 m", "100 m", "10 m", "10000 m"], dogru: "1000 m" },
      { soru: "1 ton kaç kilogramdır?", secenekler: ["1000 kg", "100 kg", "10 kg", "10000 kg"], dogru: "1000 kg" },
      { soru: "1 saat kaç dakikadır?", secenekler: ["60 dakika", "30 dakika", "100 dakika", "120 dakika"], dogru: "60 dakika" },
      { soru: "1 dakika kaç saniyedir?", secenekler: ["60 saniye", "30 saniye", "100 saniye", "12 saniye"], dogru: "60 saniye" },
      { soru: "Bilimsel yöntemin basamakları hangi sıradadır?", secenekler: ["Gözlem → Hipotez → Deney → Sonuç", "Deney → Hipotez → Gözlem → Sonuç", "Sonuç → Hipotez → Deney → Gözlem", "Hipotez → Sonuç → Deney → Gözlem"], dogru: "Gözlem → Hipotez → Deney → Sonuç" },
      { soru: "Fizikte model neyi ifade eder?", secenekler: ["Gerçeğin basitleştirilmiş gösterimi", "Gerçeğin kendisi", "Deney sonucu", "Teorinin kanıtı"], dogru: "Gerçeğin basitleştirilmiş gösterimi" },
      { soru: "Fizik kanunu neyi belirtir?", secenekler: ["Doğa olayları arasındaki ilişkiyi", "Deney sonucunu", "Ölçüm birimini", "Model açıklamasını"], dogru: "Doğa olayları arasındaki ilişkiyi" },
      { soru: "1 cm kaç mm'dir?", secenekler: ["10 mm", "100 mm", "1 mm", "1000 mm"], dogru: "10 mm" },
      { soru: "1 mm kaç mikrometredir?", secenekler: ["1000 µm", "100 µm", "10 µm", "10000 µm"], dogru: "1000 µm" },
      { soru: "1 g kaç mg'dir?", secenekler: ["1000 mg", "100 mg", "10 mg", "10000 mg"], dogru: "1000 mg" },
      { soru: "1 kg kaç gramdır?", secenekler: ["1000 g", "100 g", "10 g", "10000 g"], dogru: "1000 g" },
      { soru: "1 ml kaç cm³'tür?", secenekler: ["1 cm³", "10 cm³", "0.1 cm³", "100 cm³"], dogru: "1 cm³" },
      { soru: "1 L kaç dm³'tür?", secenekler: ["1 dm³", "10 dm³", "0.1 dm³", "100 dm³"], dogru: "1 dm³" },
      { soru: "Ölçümün hassasiyeti neyi belirtir?", secenekler: ["Yapılabilen en küçük ölçüm", "Yapılabilen en büyük ölçüm", "Ortalama ölçüm", "Toplam ölçüm"], dogru: "Yapılabilen en küçük ölçüm" },
      { soru: "Ölçümün doğruluğu neyi belirtir?", secenekler: ["Gerçek değere yakınlık derecesi", "Ölçüm aralığı", "Ölçüm hızı", "Ölçüm birimi"], dogru: "Gerçek değere yakınlık derecesi" },
      { soru: "Bilimsel gösterim 1.000.000 nasıl yazılır?", secenekler: ["1×10⁶", "1×10⁵", "1×10⁷", "1×10⁴"], dogru: "1×10⁶" },
      { soru: "Bilimsel gösterim 0.000001 nasıl yazılır?", secenekler: ["1×10⁻⁶", "1×10⁻⁵", "1×10⁻⁷", "1×10⁻⁴"], dogru: "1×10⁻⁶" },
      { soru: "Fizikte değişken nedir?", secenekler: ["Değeri değişebilen büyüklük", "Değeri sabit büyüklük", "Sadece ölçülen büyüklük", "Sadece hesaplanan büyüklük"], dogru: "Değeri değişebilen büyüklük" },
      { soru: "Fizikte sabit nedir?", secenekler: ["Değeri değişmeyen büyüklük", "Değeri değişen büyüklük", "Sadece zamanla değişen", "Sadece yere göre değişen"], dogru: "Değeri değişmeyen büyüklük" },
      { soru: "Yasal büyükten küçüğe doğru kullanılan önek hangisidir?", secenekler: ["m, dm, cm, mm", "mm, cm, dm, m", "cm, dm, m, mm", "dm, cm, mm, m"], dogru: "m, dm, cm, mm" },
      { soru: "1000 birimlik birim sistemi hangisidir?", secenekler: ["SI (Sistème International d'Unités)", "CGS (Centimetre-Gramme-Second)", "MKS (Metre-Kilogramme-Second)", "FPS (Foot-Pound-Second)"], dogru: "SI (Sistème International d'Unités)" },
      { soru: "SI birim sistemine göre sıcaklık birimi nedir?", secenekler: ["Kelvin (K)", "Celsius (°C)", "Fahrenheit (°F)", "Rankine (°R)"], dogru: "Kelvin (K)" },
      { soru: "SI birim sistemine göre elektrik akımı birimi nedir?", secenekler: ["Amper (A)", "Volt (V)", "Ohm (Ω)", "Watt (W)"], dogru: "Amper (A)" },
      { soru: "SI birim sistemine göre madde miktarı birimi nedir?", secenekler: ["mol (mol)", "gram (g)", "kilogram (kg)", "litre (L)"], dogru: "mol (mol)" },
      { soru: "Avogadro sayısı yaklaşık kaçtır?", secenekler: ["6.02×10²³", "3.14×10²³", "1.6×10⁻¹⁹", "9.8×10²³"], dogru: "6.02×10²³" },
      { soru: "Işık hızı boşlukta yaklaşık kaç km/s'dir?", secenekler: ["300.000 km/s", "150.000 km/s", "450.000 km/s", "100.000 km/s"], dogru: "300.000 km/s" },
      { soru: "Ses hızı oda sıcaklığında havada yaklaşık kaç m/s'dir?", secenekler: ["340 m/s", "150 m/s", "500 m/s", "1000 m/s"], dogru: "340 m/s" },
      { soru: "Yer çekimi ivmesi yaklaşık kaç m/s²'dir?", secenekler: ["9.8 m/s²", "5 m/s²", "15 m/s²", "20 m/s²"], dogru: "9.8 m/s²" },
      { soru: "Standart atmosfer basıncı yaklaşık kaç Pascal'dır?", secenekler: ["101.325 Pa", "100.000 Pa", "102.325 Pa", "99.325 Pa"], dogru: "101.325 Pa" },
      { soru: "Su donma noktasında kaç derece Celsius'tir?", secenekler: ["0°C", "-10°C", "10°C", "-5°C"], dogru: "0°C" },
      { soru: "Su kaynama noktasında kaç derece Celsius'tir?", secenekler: ["100°C", "90°C", "110°C", "95°C"], dogru: "100°C" },
      { soru: "Absolut sıfır kaç derece Celsius'tir?", secenekler: ["-273°C", "-200°C", "-300°C", "-250°C"], dogru: "-273°C" },
      { soru: "Absolut sıfır kaç derece Kelvindir?", secenekler: ["0 K", "-273 K", "273 K", "100 K"], dogru: "0 K" },
      { soru: "Oda sıcaklığı yaklaşık kaç derece Kelvindir?", secenekler: ["300 K", "273 K", "27 K", "373 K"], dogru: "300 K" },
      { soru: "Vücut sıcaklığı yaklaşık kaç derece Celsius'tir?", secenekler: ["37°C", "35°C", "40°C", "30°C"], dogru: "37°C" },
      { soru: "Vücut sıcaklığı yaklaşık kaç derece Kelvindir?", secenekler: ["310 K", "300 K", "273 K", "373 K"], dogru: "310 K" },
      { soru: "Astronomik birim (AU) ne için kullanılır?", secenekler: ["Gök cisimleri arası mesafeler", "Atomik ölçümler", "Mikroskobik ölçümler", "Kütle ölçümü"], dogru: "Gök cisimleri arası mesafeler" },
      { soru: "Işık yılı yaklaşık kaç km'dir?", secenekler: ["9.46×10¹² km", "10¹⁰ km", "10⁸ km", "10⁶ km"], dogru: "9.46×10¹² km" },
      { soru: "Parsek (pc) ne için kullanılır?", secenekler: ["Yıldızlar arası mesafeler", "Atomik ölçümler", "Dünya üzerindeki mesafeler", "Kütle ölçümü"], dogru: "Yıldızlar arası mesafeler" },
      { soru: "Nanometre (nm) hangi ölçümde kullanılır?", secenekler: ["Çok küçük uzunluklar", "Çok büyük uzunluklar", "Kütle ölçümü", "Zaman ölçümü"], dogru: "Çok küçük uzunluklar" },
      { soru: "1 nm yaklaşık kaç metredir?", secenekler: ["10⁻⁹ m", "10⁻⁶ m", "10⁻¹² m", "10⁻³ m"], dogru: "10⁻⁹ m" },
      { soru: "DNA çapı yaklaşık kaç nm'dir?", secenekler: ["2 nm", "1 nm", "10 nm", "0.1 nm"], dogru: "2 nm" },
      { soru: "Atom çapı yaklaşık kaç nm'dir?", secenekler: ["0.1 nm", "1 nm", "10 nm", "0.01 nm"], dogru: "0.1 nm" },
      { soru: "Yarıçapı yaklaşık 3000 km olan gezegen hangisidir?", secenekler: ["Merkür", "Venüs", "Dünya", "Mars"], dogru: "Merkür" },
      { soru: "Yarıçapı yaklaşık 6400 km olan gezegen hangisidir?", secenekler: ["Dünya", "Mars", "Venüs", "Merkür"], dogru: "Dünya" },
      { soru: "Ay'ın yörünge periyodu yaklaşık kaç gündür?", secenekler: ["27.3 gün", "30 gün", "365 gün", "24 saat"], dogru: "27.3 gün" },
      { soru: "Dünya'nın güneş etrafında dolan periyodu nedir?", secenekler: ["365.25 gün", "27.3 gün", "24 saat", "30 gün"], dogru: "365.25 gün" },
      { soru: "Dünya'nın kendi ekseni etrafında dönme periyodu nedir?", secenekler: ["24 saat", "365 gün", "27.3 gün", "30 gün"], dogru: "24 saat" },
      { soru: "Birim dönüşümlerde 1 inç kaç cm'dir?", secenekler: ["2.54 cm", "2 cm", "3 cm", "2.5 cm"], dogru: "2.54 cm" },
      { soru: "Birim dönüşümlerde 1 mil kaç km'dir?", secenekler: ["1.609 km", "1.5 km", "2 km", "1.2 km"], dogru: "1.609 km" },
      { soru: "Birim dönüşümlerde 1 mil deniz kaç km'dir?", secenekler: ["1.852 km", "1.609 km", "2 km", "1.5 km"], dogru: "1.852 km" },
      { soru: "Birim dönüşümlerde 1 pound kaç gramdır?", secenekler: ["453.6 g", "500 g", "400 g", "550 g"], dogru: "453.6 g" },
      { soru: "Birim dönüşümlerde 1 pound kaç kg'dır?", secenekler: ["0.4536 kg", "0.5 kg", "0.4 kg", "0.55 kg"], dogru: "0.4536 kg" },
      { soru: "Ölçüm hatalarının kaynakları nelerdir?", secenekler: ["Alet hatası, gözlemci hatası, çevresel etkiler", "Sadece alet hatası", "Sadece gözlemci hatası"], dogru: "Alet hatası, gözlemci hatası, çevresel etkiler" },
      { soru: "Sistematik hata nedir?", secenekler: ["Her ölçümde aynı yönde olan hata", "Rastgele olan hata", "Yanlış kalibrasyon hatası", "Okuma hatası"], dogru: "Her ölçümde aynı yönde olan hata" },
      { soru: "Rastgele hata nedir?", secenekler: ["Öngörülemeyen değişken hatalar", "Sabit olan hata", "Kalibrasyon hatası", "Alet hatası"], dogru: "Öngörülemeyen değişken hatalar" },
      { soru: "Mutlak hata nedir?", secenekler: ["Gerçek değer - ölçülen değer", "Ölçülen değer - gerçek değer", "Gerçek değer + ölçülen değer", "Gerçek değer × ölçülen değer"], dogru: "Gerçek değer - ölçülen değer" },
      { soru: "Göreceli hata nedir?", secenekler: ["|Mutlak hata| / gerçek değer", "Gerçek değer / |Mutlak hata|", "Mutlak hata × gerçek değer", "Mutlak hata + gerçek değer"], dogru: "|Mutlak hata| / gerçek değer" },
      { soru: "Yüzde hata nasıl hesaplanır?", secenekler: ["Göreceli hata × 100%", "Mutlak hata × 100%", "Göreceli hata / 100%", "Mutlak hata / 100%"], dogru: "Göreceli hata × 100%" },
      { soru: "Anlamlı rakamlar nedir?", secenekler: ["Güvenilir rakamlar", "Tahmini rakamlar", "Yanlış rakamlar", "Tam rakamlar"], dogru: "Güvenilir rakamlar" },
      { soru: "12.340 beş anlamlı rakamı vardır?", secenekler: ["5", "4", "3", "6"], dogru: "5" },
      { soru: "0.00120 beş anlamlı rakamı vardır?", secenekler: ["5", "3", "4", "6"], dogru: "5" },
      { soru: "Yuvarlama kurallarında 0.5'ten büyük sayılar nasıl yuvarlanır?", secenekler: ["Bir üst tam sayıya", "Bir alt tam sayıya", "En yakın tam sayıya", "Yuvarlanmaz"], dogru: "Bir üst tam sayıya" },
      { soru: "Yuvarlama kurallarında 0.5'ten küçük sayılar nasıl yuvarlanır?", secenekler: ["Bir alt tam sayıya", "Bir üst tam sayıya", "En yakın tam sayıya", "Yuvarlanmaz"], dogru: "Bir alt tam sayıya" },
      { soru: "3.4 sayısı tam sayıya nasıl yuvarlanır?", secenekler: ["3", "4", "2", "5"], dogru: "3" },
      { soru: "3.5 sayısı tam sayıya nasıl yuvarlanır?", secenekler: ["4", "3", "2", "5"], dogru: "4" },
      { soru: "3.6 sayısı tam sayıya nasıl yuvarlanır?", secenekler: ["4", "3", "2", "5"], dogru: "4" },
      { soru: "Significant figures (anlamlı rakamlar) hesabında 2.5 × 3.5 işleminin sonucu kaç anlamlı rakamlı olmalıdır?", secenekler: ["2", "3", "1", "4"], dogru: "2" },
      { soru: "Significant figures hesabında 5.0 × 2.0 işleminin sonucu kaç anlamlı rakamlı olmalıdır?", secenekler: ["2", "1", "3", "4"], dogru: "2" },
      { soru: "Boyut analizi nedir?", secenekler: ["Birim tutarlılığı kontrol etme", "Soru kalitesini kontrol etme", "Deney sonucunu kontrol etme", "Model doğruğunu kontrol etme"], dogru: "Birim tutarlılığı kontrol etme" },
      { soru: "F = m × a formülünde boyut analizi yapılırsa birim ne olur?", secenekler: ["kg·m/s² = N", "kg·m²/s²", "kg/(m·s²)", "kg²·m/s²"], dogru: "kg·m/s² = N" },
      { soru: "E = m × c² formülünde c'nin birimi nedir?", secenekler: ["m/s", "m/s²", "kg·m/s", "J·s"], dogru: "m/s" },
      { soru: "Fizikte nicel büyüklük hangisidir?", secenekler: ["Ölçülebilir ve sayısal ifade edilebilen", "Sadece hissedilen", "Sadece gözlemlenen", "Sadece tahmin edilen"], dogru: "Ölçülebilir ve sayısal ifade edilebilen" },
      { soru: "Fizikte vektörel büyüklük hangisidir?", secenekler: ["Büyüklüğü ve yönü olan", "Sadece büyüklüğü olan", "Sadece yönü olan", "Sayısal olmayan"], dogru: "Büyüklüğü ve yönü olan" },
      { soru: "Aşağıdakiler hangisi vektörel büyüklük değildir?", secenekler: ["kütle", "kuvvet", "hız", "ivme"], dogru: "kütle" },
      { soru: "Aşağıdakiler hangisi skaler büyüklüktür?", secenekler: ["enerji", "kuvvet", "hız", "yer değiştirme"], dogru: "enerji" },
      { soru: "Vektörel büyüklüklerin toplamı nasıl yapılır?", secenekler: ["Paralelkenköşegen kuralı", "Doğrudan toplama", "Büyüklüklerini topla, yönlerini görmezden gel", "Sadece yönlerini topla"], dogru: "Paralelkenköşegen kuralı" },
      { soru: "Fizikte integral ne işe yarar?", secenekler: ["Değişim oranını hesaplama", "Sabit değerleri bulma", "Toplam değeri bulma", "Ortalama değeri bulma"], dogru: "Değişim oranını hesaplama" },
      { soru: "Fizikte türev neyi gösterir?", secenekler: ["Değişim oranını", "Toplam değeri", "Ortalama değeri", "Maksimum değeri"], dogru: "Değişim oranını" },
      { soru: "Fizikte alan altı integral neyi gösterir?", secenekler: ["Toplam değeri veya birikimi", "Değişim oranını", "Ortalama değeri", "Anlık değeri"], dogru: "Toplam değeri veya birikimi" },
      { soru: "Grafikte eğim neyi gösterir?", secenekler: ["Değişim oranını", "Toplam değeri", "Sabit değeri", "Maksimum değeri"], dogru: "Değişim oranını" },
      { soru: "Grafikte alan altı neyi gösterir?", secenekler: ["Toplam değeri veya birikimi", "Değişim oranını", "Ortalama değeri", "Anlık değeri"], dogru: "Toplam değeri veya birikimi" },
      { soru: "x-t grafiğinde eğim birimi nedir?", secenekler: ["y/x", "x/y", "y×x", "y+x"], dogru: "y/x" },
      { soru: "v-t grafiğinde alan altı neyi gösterir?", secenekler: ["Yer değiştirme", "Hız", "İvme", "Kuvvet"], dogru: "Yer değiştirme" },
      { soru: "Fizikte model neden gereklidir?", secenekler: ["Karmaşık sistemleri basitleştirmek için", "Gerçeği tam olarak yansıtmak için", "Deneyleri zorlaştırmak için", "Hesaplamaları yapıştırmak için"], dogru: "Karmaşık sistemleri basitleştirmek için" },
      { soru: "Fizikte teori nedir?", secenekler: ["Doğa olaylarını açıklayan kanunlar bütünü", "Tek bir deney sonucu", "Bir varsayım", "Bir ölçüm sonucu"], dogru: "Doğa olaylarını açıklayan kanunlar bütünü" },
      { soru: "Bir teori ne zaman kanun olur?", secenekler: ["Birden çok deneyle doğrulandığında", "Tek bir deneyle doğrulandığında", "Sadece matematiksel olarak kanıtlandığında", "Bilim insanının kabul etmesiyle"], dogru: "Birden çok deneyle doğrulandığında" },
      { soru: "Newton'un hareket yasaları hangi durumlarda geçerlidir?", secenekler: ["Küçük hızlarda", "Büyük hızlarda", "Sadece uzayda", "Sadece dünyada"], dogru: "Küçük hızlarda" },
      { soru: "Einstein'in görelilik teorisi hangi durumlarda gereklidir?", secenekler: ["Büyük hızlarda veya güçlü yer çekiminde", "Küçük hızlarda", "Sadece dünyada", "Sadece laboratuvarda"], dogru: "Büyük hızlarda veya güçlü yer çekiminde" },
      { soru: "Kuantum mekaniği hangi ölçekte geçerlidir?", secenekler: ["Atomik ve atom altı ölçekte", "Günlük ölçeğinde", "Gezegen ölçeğinde", "Evren ölçeğinde"], dogru: "Atomik ve atom altı ölçekte" },
      { soru: "Klasik fizik hangi ölçekte geçerlidir?", secenekler: ["Günlük ölçeğinde", "Atomik ölçeğinde", "Atom altı ölçeğinde", "Subatomik ölçeğinde"], dogru: "Günlük ölçeğinde" },
      { soru: "Planck sabiti neyi ilişkilendirir?", secenekler: ["Kuantum mekaniği", "Görelilik teorisi", "Termodinamik", "Elektromanyetizma"], dogru: "Kuantum mekaniği" },
      { soru: "Işık hızı c = 3×10⁸ m/s hangi teoride sabittir?", secenekler: ["Görelilik teorisi", "Kuantum mekaniği", "Newton mekaniği", "Termodinamik"], dogru: "Görelilik teorisi" },
      { soru: "E = mc² formülü kime aittir?", secenekler: ["Einstein", "Newton", "Planck", "Bohr"], dogru: "Einstein" },
      { soru: "F = ma formülü kime aittir?", secenekler: ["Newton", "Einstein", "Planck", "Bohr"], dogru: "Newton" },
      { soru: "Heisenberg belirsizlik ilkesi neyi ifade eder?", secenekler: ["Konum ve momentum aynı anda hassas ölçülemez", "Işık hızı sabittir", "Enerji korunur", "Madde korunur"], dogru: "Konum ve momentum aynı anda hassas ölçülemez" },
      { soru: "Schrödinger denklemi neyi ifade eder?", secenekler: ["Kuantum sisteminin davranışını", "Klasik sistemin davranışını", "Görelilik etkilerini", "Termodinamik davranışı"], dogru: "Kuantum sisteminin davranışını" },
      { soru: "Yarı iletkenler arasında hangisi süper iletken olabilir?", secenekler: ["Düşük sıcaklıkta", "Yüksek sıcaklıkta", "Oda sıcaklığında", "Her sıcaklıkta"], dogru: "Düşük sıcaklıkta" },
      { soru: "Lazer ne üretir?", secenekler: ["Koherent ışık", "Koherensiz ışık", "Radyo dalgaları", "X ışınları"], dogru: "Koherent ışık" },
      { soru: "Nükleer fisyon ne demektir?", secenekler: ["Ağır çekirdeğin hafif çekirdeklere bölünmesi", "Hafif çekirdeğin birleşmesi", "Nötron boşunması", "Elektron yakalanması"], dogru: "Ağır çekirdeğin hafif çekirdeklere bölünmesi" },
      { soru: "Nükleer füzyon ne demektir?", secenekler: ["Hafif çekirdeğin ağır çekirdek oluşturması", "Ağır çekirdeğin bölünmesi", "Nötron boşunması", "Elektron yakalanması"], dogru: "Hafif çekirdeğin ağır çekirdek oluşturması" },
      { soru: "Nükleer enerji santrallerinde hangi reaksiyon kullanılır?", secenekler: ["Fisyon", "Füzyon", "Kimyasal reaksiyon", "Mekanik reaksiyon"], dogru: "Fisyon" },
      { soru: "Güneş enerjisinin kaynağı nedir?", secenekler: ["Füzyon", "Fisyon", "Kimyasal reaksiyon", "Mekanik hareket"], dogru: "Füzyon" },
      { soru: "Radyoaktivite hangi parçacık yayılmasına neden olur?", secenekler: ["Alpha, beta, gama", "Sadece alpha", "Sadece beta", "Sadece gama"], dogru: "Alpha, beta, gama" },
      { soru: "Yarı ömür neyi ifade eder?", secenekler: ["Radyoaktif maddenin yarısının parçalanma süresi", "Maddenin tamamının parçalanma süresi", "Maddenin oluşma süresi", "Maddenin ömrü"], dogru: "Radyoaktif maddenin yarısının parçalanma süresi" },
      { soru: "Carbon-14 tarihlama ne için kullanılır?", secenekler: ["Organik kalıntıların yaşı tespiti", "Kayaçların yaşı tespiti", "Yıldızların yaşı tespiti", "Denizlerin yaşı tespiti"], dogru: "Organik kalıntıların yaşı tespiti" },
      { soru: "X-ışınları tıpta nasıl kullanılır?", secenekler: ["Görüntüleme", "Tedavi", "Ameliyat", "Tanı ve tedavi"], dogru: "Görüntüleme" },
      { soru: "Manyetik rezonans görüntüleme (MRI) neye dayanır?", secenekler: ["Hidrojen çekirdeklerinin manyetik özellikleri", "X ışınları", "Ses dalgaları", "Radyo dalgaları"], dogru: "Hidrojen çekirdeklerinin manyetik özellikleri" },
      { soru: "Positron emisyon tomografisi (PET) neyi kullanır?", secenekler: ["Pozitron yayan izotoplar", "Alfa yayan izotoplar", "Beta yayan izotoplar", "Gama yayan izotoplar"], dogru: "Pozitron yayan izotoplar" },
      { soru: "Radyoterapi kanser tedavisinde nasıl çalışır?", secenekler: ["Kanser hücrelerini radyasyonla yok etmek", "Sağlı hücreleri güçlendirmek", "Bağışıklık sistemini uyarmak", "Vücudu ısıtmak"], dogru: "Kanser hücrelerini radyasyonla yok etmek" },
      { soru: "Sibren deneyi neyi kanıtladı?", secenekler: ["Elektronların dalga yapısını", "Elektronların parçacık yapısını", "Işığın parçacık yapısını", "Kütlenin parçacık yapısını"], dogru: "Elektronların dalga yapısını" },
      { soru: "Fotoelektrik etki neyi açıklar?", secenekler: ["Işığın maddelerden elektron koparabilmesi", "Elektronların ışık yayabilmesi", "Isıların maddeleri ısıtması", "Maddelerin genleşmesi"], dogru: "Işığın maddelerden electron koparabilmesi" },
      { soru: "Compton saçılması neyi açıklar?", secenekler: ["Fotonların elektronlarla saçılması", "Elektronların fotonların yayılması", "Fotonların fotonların saçılması", "Elektronların electronların saçılması"], dogru: "Fotonların electronlarla saçılması" },
      { soru: "Dalga-parçacık ikiliği neyi ifade eder?", secenekler: ["Maddenin hem dalga hem parçacık özellikleri göstermesi", "Sadece dalga özelliği", "Sadece parçacık özelliği", "Ne dalga ne parçacık"], dogru: "Maddenin hem dalga hem parçacık özellikleri göstermesi" },
      { soru: "Süper iletkenler sürekli akım taşırlar mı?", secenekler: ["Evet, dirençsüz", "Hayır, az miktarlarda", "Sadece düşük sıcaklıkta", "Sadece yüksek voltajda"], dogru: "Evet, dirençsüz" },
      { soru: "Hall etkisi neyi ifade eder?", secenekler: ["Manyetik alanın akımı saptırması", "Isılığın akımı saptırması", "Mekanik basıncın akımı saptırması", "Elektrik alanın akımı saptırması"], dogru: "Manyetik alanın akımı saptırması" },
      { soru: "Süper akışkanlık nedir?", secenekler: ["Sıfır direnç", "Çok düşük direnç", "Yüksek direnç", "Sınırsız iletkenlik"], dogru: "Sıfır direnç" },
      { soru: "Meissner efekti nedir?", secenekler: ["Süper iletkenlerin manyetik alanı dışlama özelliği", "Süper iletkenlerin ısıtma özelliği", "Süper iletkenlerin elektrik üretme özelliği", "Süper iletkenlerin soğuma özelliği"], dogru: "Süper iletkenlerin manyetik alanı dışlama özelliği" },
      { soru: "Nanoteknoloji hangi ölçekte çalışır?", secenekler: ["1-100 nm", "1-10 µm", "1-10 mm", "1-10 cm"], dogru: "1-100 nm" },
      { soru: "Graphene özel bir malzeme çünkü?", secenekler: ["Tek atom kalınlığındaki karbon", "İki atom kalınlığındaki karbon", "Üç atom kalınlığındaki karbon", "Dört atom kalınlığındaki karbon"], dogru: "Tek atom kalınlığındaki karbon" },
      { soru: "Karanlık madde nedir?", secenekler: ["Gözlemlenen ama açıklanamayan madde", "Sadece teorik olan madde", "Deneysel olarak kanıtlanmış madde", "Hiçbir özelliği olmayan madde"], dogru: "Gözlemlenen ama açıklanamayan madde" },
      { soru: "Karanlık enerji nedir?", secenekler: ["Evrenin genişlemesini hızlandıran gizemli enerji", "Evrenin yok olmasına neden olan enerji", "Karanlık maddenin enerjisi", "Kara deliklerin enerjisi"], dogru: "Evrenin genişlemesini hızlandıran gizemli enerji" },
      { soru: "Siyah delin neyi ifade eder?", secenekler: ["Işığı bile yakalamayan çok yoğun kütle", "Işığı yayan çok parlak kütle", "Çok büyük bir yıldız", "Çok küçük bir yıldız"], dogru: "Işığı bile yakalamayan çok yoğun kütle" },
      { soru: "Big Bang teorisi neyi açıklar?", secenekler: ["Evrenin başlangıcını ve genişlemesini", "Sadece güneş sisteminin oluşumunu", "Sadece yıldızların oluşumunu", "Sadece dünyanın oluşumunu"], dogru: "Evrenin başlangıcını ve genişlemesini" },
      { soru: "Kozmik mikrodalga arka plan ışıması nedir?", secenekler: ["Evrenin ilk dönemlerinden gelen ışık", "Yıldızların yaydığı ışık", "Galaksilerin yansıttığı ışık", "Karanlık maddenin yaydığı ışık"], dogru: "Evrenin ilk dönemlerinden gelen ışık" },
      { soru: "Kızılaötesi (infrared) ışınları kaynağı nedir?", secenekler: ["Sıcak cisimler", "Soğuk cisimler", "Parlayan cisimler", "Yansıyan cisimler"], dogru: "Sıcak cisimler" },
      { soru: "Ultraviyole ışınları kaynağı nedir?", secenekler: ["Çok sıcak cisimler", "Soğuk cisimler", "Sadece güneş", "Sadece ampuller"], dogru: "Çok sıcak cisimler" },
      { soru: "X-ışınları nasıl üretilir?", secenekler: ["Yüksek enerjili elektron geçişleri", "Düşük enerjili elektron geçişleri", "Isıtma", "Sıkıştırma"], dogru: "Yüksek enerjili elektron geçişleri" },
      { soru: "Gamma ışınları kaynağı nedir?", secenekler: ["Nükleer geçişler", "Elektron geçişleri", "Isıtma", "Sıkıştırma"], dogru: "Nükleer geçişler" },
      { soru: "Radyo dalgaları nasıl üretilir?", secenekler: ["Hızlandırılan yüklerin salınımı", "Isıtma", "Sıkıştırma", "Aydınlatma"], dogru: "Hızlandırılan yüklerin salınımı" }
    ]},
    { ad: "Kuvvet ve Hareket", sorular: [
      { soru: "Kuvvet birimi nedir?", secenekler: ["Newton (N)", "Joule (J)", "Watt (W)", "Pascal (Pa)"], dogru: "Newton (N)" },
      { soru: "Newton birinci yasası nedir?", secenekler: ["Dengedeki cisim dengede kalır", "F = ma", "Etki-tepki eşittir", "Enerji korunumu"], dogru: "Dengedeki cisim dengede kalır" },
      { soru: "Newton ikinci yasası nedir?", secenekler: ["F = ma", "Dengedeki cisim dengede kalır", "Etki-tepki eşittir", "Enerji korunumu"], dogru: "F = ma" },
      { soru: "Newton üçüncü yasası nedir?", secenekler: ["Etki-tepki eşittir", "F = ma", "Dengedeki cisim dengede kalır", "Enerji korunumu"], dogru: "Etki-tepki eşittir" },
      { soru: "Eylemsizlik durumu ne demektir?", secenekler: ["Denge durumu", "Hızlanma durumu", "Dönme durumu", "Sıkışma durumu"], dogru: "Denge durumu" },
      { soru: "Hız birimi nedir?", secenekler: ["m/s", "m", "s", "m/s²"], dogru: "m/s" },
      { soru: "İvme birimi nedir?", secenekler: ["m/s²", "m/s", "m", "s"], dogru: "m/s²" },
      { soru: "5 N kuvvet 2 kg kütleli cismi uygulandığında ivme kaç m/s²'dir?", secenekler: ["2.5", "10", "0.4", "7"], dogru: "2.5" },
      { soru: "10 kg kütleli cismi 5 m/s² ivmeyle hareket ediyorsa kuvvet kaç N'dir?", secenekler: ["50", "2", "15", "0.5"], dogru: "50" },
      { soru: "Sürtünme kuvveti doğrultusu nasıldır?", secenekler: ["Hareket zıt yönünde", "Hareket yönünde", "Hareket yönüne dik", "Hareket yönünde 45°"], dogru: "Hareket zıt yönünde" },
      { soru: "Yer çekimi kuvveti doğrultusu nasıldır?", secenekler: ["Yer merkezi doğru", "Yer merkezinden uzak", "Yatay doğru", "Rastgele"], dogru: "Yer merkezi doğru" },
      { soru: "Normal kuvvet doğrultusu nasıldır?", secenekler: ["Yüzeye dik, dışa doğru", "Yüzeye paralel, dışa doğru", "Yüzeye dik, içe doğru"], dogru: "Yüzeye dik, dışa doğru" },
      { soru: "Gerilme kuvveti doğrultusu nasıldır?", secenekler: ["Yüzeye paralel, hareket zıt yönünde", "Yüzeye dik, dışa doğru", "Yüzeye dik, içe doğru"], dogru: "Yüzeye paralel, hareket zıt yönünde" },
      { soru: "Statik sürtünme kinetik sürtünmeden büyüktür mü?", secenekler: ["Evet, genellikle", "Hayır, her zaman küçüktür", "Eşittirler", "Duruma bağlıdır"], dogru: "Evet, genellikle" },
      { soru: "Sürtünme katsayısı hangi arasındadır?", secenekler: ["0 ve 1 arasında", "-1 ve 0 arasında", "1 ve 10 arasında", "-10 ve -1 arasında"], dogru: "0 ve 1 arasında" },
      { soru: "Sürtünmesiz yüzeyde sürtünme katsayısı kaçtır?", secenekler: ["0", "1", "0.5", "0.1"], dogru: "0" },
      { soru: "Buz üzerinde sürtünme katsayısı yaklaşık kaçtır?", secenekler: ["0.1", "0.5", "0.9", "0.05"], dogru: "0.1" },
      { soru: "Kum üzerinde sürtünme katsayısı yaklaşık kaçtır?", secenekler: ["0.5", "0.1", "0.9", "0.05"], dogru: "0.5" },
      { soru: "Serbest düşme sırasında ivme kaç m/s²'dir?", secenekler: ["9.8", "0", "5", "15"], dogru: "9.8" },
      { soru: "Serbest düşen bir cisim 3 saniyede ne kadar yol alır?", secenekler: ["44.1 m", "45 m", "30 m", "60 m"], dogru: "44.1 m" },
      { soru: "Yere fırlatılan bir cisim 2 saniyede yere dönerse yükseklik kaç metredir?", secenekler: ["19.6", "20", "15", "25"], dogru: "19.6" },
      { soru: "Yatay atılan bir cisim menzil nasıl hesaplanır?", secenekler: ["x = v₀t", "x = gt²", "x = vt²", "x = v₀/g"], dogru: "x = v₀t" },
      { soru: "Dik yukarı atılan bir cisim maksimum yüksekliği nasıl hesaplanır?", secenekler: ["h = v₀²/2g", "h = v₀²/g", "h = v₀t", "h = gt²"], dogru: "h = v₀²/2g" },
      { soru: "Dik yukarı atılan bir cisim uçuş süresi nasıl hesaplanır?", secenekler: ["t = 2v₀/g", "t = v₀/g", "t = v₀²/2g", "t = √(2h/g)"], dogru: "t = 2v₀/g" },
      { soru: "Eş değişkenli hareket nedir?", secenekler: ["Sabit ivmeli hareket", "Sabit hızlı hareket", "İvmesiz hareket", "Hızlanan hareket"], dogru: "Sabit ivmeli hareket" },
      { soru: "Sabit hızlı hareket eden cisimde ivme nedir?", secenekler: ["0", "sabit", "değişken", "sonsuz"], dogru: "0" },
      { soru: "Yavaşlayan cisim ivmesi nasıldır?", secenekler: ["Negatif", "Pozitif", "Sıfır", "Sonsuz"], dogru: "Negatif" },
      { soru: "Hızlanan cisim ivmesi nasıldır?", secenekler: ["Pozitif", "Negatif", "Sıfır", "Sonsuz"], dogru: "Pozitif" },
      { soru: "Hız-zaman grafiğinde eğim neyi gösterir?", secenekler: ["İvmeyi", "Hızı", "Yer değiştirmeyi", "Kuvveti"], dogru: "İvmeyi" },
      { soru: "Yer değiştirme-zaman grafiğinde alan altı neyi gösterir?", secenekler: ["Yer değiştirmeyi", "Hızı", "İvmeyi", "Kuvveti"], dogru: "Yer değiştirmeyi" },
      { soru: "Hız-zaman grafiğinde doğrunun altında kalan alan neyi gösterir?", secenekler: ["Alınan yol", "Hızlanma", "Yavaşlama", "Sabit hız"], dogru: "Alınan yol" },
      { soru: "Eşsiz maddeler için momentum korunumu neyi ifade eder?", secenekler: ["Toplam momentum sabittir", "Toplam kuvvet sıfırdır", "Toplam enerji sabittir", "Toplam kütle sabittir"], dogru: "Toplam momentum sabittir" },
      { soru: "Momentum formülü nedir?", secenekler: ["p = mv", "p = ma", "p = mv²", "p = mgh"], dogru: "p = mv" },
      { soru: "Momentum birimi nedir?", secenekler: ["kg·m/s", "kg·m/s²", "kg·m²/s²", "kg·m/s²"], dogru: "kg·m/s" },
      { soru: "İmpulsmoment (Ağırlik) nedir?", secenekler: ["F·t", "m·a", "m·v", "m·g"], dogru: "F·t" },
      { soru: "İmpuls-momentum teoremi neyi ifade eder?", secenekler: ["Kuvvet-zaman çarpımı momentum değişimine eşittir", "Kuvvet kütleyle orantılıdır", "Momentum zamanla artar", "İmpuls her zaman sabittir"], dogru: "Kuvvet-zaman çarpımı momentum değişimine eşittir" },
      { soru: "Çarpışma sırasında ne korunur?", secenekler: ["Momentum ve toplam enerji", "Sadece momentum", "Sadece enerji", "Sadece kütle"], dogru: "Momentum ve toplam enerji" },
      { soru: "Tam esnek çarpışmada ne korunur?", secenekler: ["Momentum ve kinetik enerji", "Sadece momentum", "Sadece kinetik enerji", "Sadece kütle"], dogru: "Momentum ve kinetik enerji" },
      { soru: "Tam esnek olmayan çarpışmada ne korunur?", secenekler: ["Momentum, kinetik enerji korunmaz", "Sadece momentum", "Sadece kinetik enerji", "Hepsi korunur"], dogru: "Momentum, kinetik enerji korunmaz" },
      { soru: "Korunum yasası çarpışmalar için hangi durumlarda geçerlidir?", secenekler: ["Yalıtık sistem", "Her durumda", "Sadece dünyada", "Sadece uzayda"], dogru: "Yalıtık sistem" },
      { soru: "Merkezcil kuvvet örnekleri nelerdir?", secenekler: ["Yer çekimi, manyetik kuvvet", "Sürtünme, gerilme", "Normal kuvvet"], dogru: "Yer çekimi, manyetik kuvvet" },
      { soru: "Temas kuvvetleri örnekleri nelerdir?", secenekler: ["Sürtünme, gerilme, normal kuvvet", "Yer çekimi", "Elektrik kuvveti"], dogru: "Sürtünme, gerilme, normal kuvvet" },
      { soru: "Aşağıdaki kuvvetlerden hangisi vektörel değildir?", secenekler: ["Yok", "Hepsi vektörel"], dogru: "Yok" },
      { soru: "Kuvvet nasıl toplanır?", secenekler: ["Paralelkenköşegen kuralı ile", "Doğrudan toplama ile", "Sadece büyüklükleri topla", "Sadece yönleri topla"], dogru: "Paralelkenköşegen kuralı ile" },
      { soru: "Aynı yöndeki iki kuvvet 10 N ve 5 N ise sonuç kaç N'dir?", secenekler: ["15 N", "5 N", "10 N", "50 N"], dogru: "15 N" },
      { soru: "Zıt yöndeki iki kuvvet 10 N ve 5 N ise sonuç kaç N'dir?", secenekler: ["5 N zıt yönde", "15 N", "5 N aynı yönde", "0 N"], dogru: "5 N zıt yönde" },
      { soru: "90° açı ile birbirine dik iki kuvvet 3 N ve 4 N ise sonuç kaç N'dir?", secenekler: ["5 N", "7 N", "1 N", "12 N"], dogru: "5 N" },
      { soru: "Kütlesiz bir cisim olabilir mi?", secenekler: ["Hayır", "Evet", "Sadece uzayda", "Sadece laboratuvarda"], dogru: "Hayır" },
      { soru: "Ağırlık ile kütle arasındaki ilişki nedir?", secenekler: ["W = mg", "W = m/g", "W = g/m", "W = m + g"], dogru: "W = mg" },
      { soru: "80 kg kişinin ağırlığı kaç N'dir (g = 10 m/s²)?", secenekler: ["800 N", "80 N", "8 N", "8000 N"], dogru: "800 N" },
      { soru: "100 kg kişinin ağırlığı kaç N'dir (g = 10 m/s²)?", secenekler: ["1000 N", "100 N", "10 N", "10000 N"], dogru: "1000 N" },
      { soru: "Ay'da yer çekimi dünyadan kaç katıdır?", secenekler: ["1/6", "1/2", "2", "3"], dogru: "1/6" },
      { soru: "Dünyada 80 kg olan bir kişi Ay'da kaç kg'dır?", secenekler: ["80 kg", "480 kg", "13.3 kg", "40 kg"], dogru: "80 kg" },
      { soru: "Dünyada 80 kg olan bir kişinin ağırlığı Ay'da kaç N'dir?", secenekler: ["133 N", "480 N", "800 N", "13 N"], dogru: "133 N" },
      { soru: "Dönen bir sisteme uygulanan kuvvetin neden olduğu etki nedir?", secenekler: ["Döndürme momenti", "Doğrusal ivme", "Yanlı ivme", "Merkezcil kuvvet"], dogru: "Döndürme momenti" },
      { soru: "Moment (tork) birimi nedir?", secenekler: ["N·m", "N/m", "N/m²", "N/m³"], dogru: "N·m" },
      { soru: "Kol uzunluğu 2 m olan bir makaraya 10 N kuvvet uygulanırsa moment kaç N·m'dir?", secenekler: ["20", "5", "8", "12"], dogru: "20" },
      { soru: "Denge koşulu nedir?", secenekler: ["Toplam tork = 0", "Toplam kuvvet = 0", "Toplam moment = 0", "Toplam enerji = 0"], dogru: "Toplam tork = 0" },
      { soru: "Basit makinelerin mekanik avantajı nedir?", secenekler: ["Küçük kuvvetle büyük iş yapabilme", "Büyük kuvvetle küçük iş yapabilme", "Hız kazanma", "Enerji tasarrufu"], dogru: "Küçük kuvvetle büyük iş yapabilme" },
      { soru: "Mekanik avantaj = 5 olan makine 100 N yükü kaldırırsa gereken kuvvet kaç N'dir?", secenekler: ["20", "500", "50", "10"], dogru: "20" },
      { soru: "Mekanik avantajı = 0.2 olan makine 50 N yükü kaldırırsa üretilen kuvvet kaç N'dir?", secenekler: ["10", "250", "100", "5"], dogru: "10" },
      { soru: "Enerji korunumu yasası mekanik sistemlerde neyi ifade eder?", secenekler: ["Potansiyel + kinetik enerji sabittir", "Kinetik enerji sabittir", "Potansiyel enerji sabittir", "Momentum sabittir"], dogru: "Potansiyel + kinetik enerji sabittir" },
      { soru: "Kinematik enerji formülü nedir?", secenekler: ["Ek = ½mv²", "Ek = mv", "Ek = ma", "Ek = mgh"], dogru: "Ek = ½mv²" },
      { soru: "Potansiyel enerji formülü nedir?", secenekler: ["Ep = mgh", "Ep = ½mv²", "Ep = ma", "Ep = mg"], dogru: "Ep = mgh" },
      { soru: "Mekanik enerji formülü nedir?", secenekler: ["Em = Ep + Ek", "Em = Ep - Ek", "Em = Ep × Ek", "Em = Ep/Ek"], dogru: "Em = Ep + Ek" },
      { soru: "5 m/s hızla giden 2 kg cismin kinetik enerjisi kaç J'dir?", secenekler: ["25", "10", "50", "5"], dogru: "25" },
      { soru: "10 m yükseklikteki 5 kg cismin potansiyel enerjisi kaç J'dir (g = 10 m/s²)?", secenekler: ["500", "250", "50", "100"], dogru: "500" },
      { soru: "4 m yükseklikten düşen 2 kg cismin yere çarpma hızı kaç m/s'dir?", secenekler: ["√80", "8", "40", "20"], dogru: "√80" },
      { soru: "Yay germe mekanik enerji örnek midir?", secenekler: ["Evet", "Hayır", "Sadece potansiyel enerji dönüşümü", "Sadece kinetik enerji dönüşümü"], dogru: "Evet" },
      { soru: "Pendül sallanması mekanik enerji örnek midir?", secenekler: ["Evet", "Hayır", "Sadece kinetik enerji vardır", "Sadece potansiyel enerji vardır"], dogru: "Evet" },
      { soru: "Sürtünme olduğunda mekanik enerji korunur mu?", secenekler: ["Hayır, ısıya dönüşür", "Evet, her zaman korunur", "Sadece kinetik enerji korunur", "Sadece potansiyel enerji korunur"], dogru: "Hayır, ısıya dönüşür" },
      { soru: "Sürtünmesiz yüzeyde mekanik enerji korunur mu?", secenekler: ["Evet", "Hayır", "Sadece kinetik enerji korunur", "Sadece potansiyel enerji korunur"], dogru: "Evet" },
      { soru: "Güç neyi ifade eder?", secenekler: ["Enerji değişim hızı", "Toplam enerji", "Kuvvet", "İvme"], dogru: "Enerji değişim hızı" },
      { soru: "Güç birimi nedir?", secenekler: ["Watt (W)", "Joule (J)", "Newton (N)", "Pascal (Pa)"], dogru: "Watt (W)" },
      { soru: "Güç formülü nedir?", secenekler: ["P = W/t", "P = W×t", "P = W/t²", "P = W×t²"], dogru: "P = W/t" },
      { soru: "İş formülü nedir?", secenekler: ["W = F·x", "W = F/x", "W = F·x²", "W = F/x²"], dogru: "W = F·x" },
      { soru: "100 N kuvvet 50 m yol alırsa iş kaç J'dir?", secenekler: ["5000", "200", "150", "5"], dogru: "5000" },
      { soru: "50 N kuvvet 100 m yol alırsa iş kaç J'dir?", secenekler: ["5000", "500", "500", "5"], dogru: "5000" },
      { soru: "5000 J iş 10 saniyede yapılırsa güç kaç W'tir?", secenekler: ["500", "50", "500", "5"], dogru: "500" },
      { soru: "1000 W güç 5 saniyede kaç iş yapar?", secenekler: ["5000 J", "200 J", "500 J", "20000 J"], dogru: "5000 J" },
      { soru: "Verimlilik (%) nedir?", secenekler: ["(Çıkış işi / Giren iş) × 100", "(Giren işi / Çıkış işi) × 100", "Çıkış işi - Giren işi", "Giren işi - Çıkış işi"], dogru: "(Çıkış işi / Giren işi) × 100" },
      { soru: "Basit makinede verimlilik 100% olabilir mi?", secenekler: ["Hayır, her zaman 100%'den küçüktür", "Evet, ideal koşullarda", "Sadece hareketli parçalar için", "Sadece sabit parçalar için"], dogru: "Hayır, her zaman 100%'den küçüktür" },
      { soru: "Eğimli düzlemde aşağı doğru hareket eden cisim için enerji korunumu nasıl yazılır?", secenekler: ["mgh = ½mv²", "mgh + ½mv² = sabit", "mgh - ½mv² = sabit", "½mv² - mgh = sabit"], dogru: "mgh + ½mv² = sabit" },
      { soru: "Eğimli düzlemde yukarı doğru hareket eden cisim için enerji korunumu nasıl yazılır?", secenekler: ["½mv² = mgh + kayıp", "mgh = ½mv² + kayıp", "mgh + ½mv² = sabit", "½mv² - mgh = sabit"], dogru: "½mv² = mgh + kayıp" },
      { soru: "Basit harmonik hareket örneği nedir?", secenekler: ["Pendül", "Serbest düşme", "Sabit ivmeli hareket", "Sabit hızlı hareket"], dogru: "Pendül" },
      { soru: "Basit harmonik harekette enerji nasıl değişir?", secenekler: ["Kinetik ve potansiyel enerji sürekli dönüşür", "Sadece kinetik enerji değişir", "Sadece potansiyel enerji değişir", "Enerji tükenir"], dogru: "Kinetik ve potansiyel enerji sürekli dönüşür" },
      { soru: "Dönüş hareketi örneği nedir?", secenekler: ["Pendül gibi salınım", "Serbest düşme", "Atış", "Yuvarlanma"], dogru: "Pendül gibi salınım" },
      { soru: "Dairesel hareket örneği nedir?", secenekler: ["İp ucuna bağlı cisim düzlemde dairesel hareket", "Serbest düşme", "Dikey atış", "Yatay atış"], dogru: "İp ucuna bağlı cisim düzlemde dairesel hareket" },
      { soru: "Dairesel hareketta hangi kuvvet belirleyicidir?", secenekler: ["Merkezcil kuvvet", "Sürtünme kuvveti", "Ağırlık", "Normal kuvvet"], dogru: "Merkezcil kuvvet" },
      { soru: "Merkezcil kuvvetin yönü nasıldır?", secenekler: ["Merkeze doğru", "Merkezden uzak", "Hareket yönünde", "Rastgele"], dogru: "Merkeze doğru" },
      { soru: "Merkezcil kuvvet formülü nedir?", secenekler: ["F = mv²/r", "F = mr²/v", "F = mvr", "F = mv/r"], dogru: "F = mv²/r" },
      { soru: "Dairesel hareketta period nasıl hesaplanır?", secenekler: ["T = 2πr/v", "T = v/2πr", "T = 2πv/r", "T = 2πrv"], dogru: "T = 2πr/v" },
      { soru: "Dairesel hareketta frekans nasıl hesaplanır?", secenekler: ["f = 1/T = v/2πr", "f = T", "f = 2πr/v", "f = v/T"], dogru: "f = 1/T = v/2πr" },
      { soru: "Açısal hız birimi nedir?", secenekler: ["rad/s", "rad", "m/s", "rad/s²"], dogru: "rad/s" },
      { soru: "Açısal ivme birimi nedir?", secenekler: ["rad/s²", "rad/s", "m/s²", "rad"], dogru: "rad/s²" },
      { soru: "Açısal hızla lineer hız arasındaki ilişki nedir?", secenekler: ["v = ωr", "v = ω/r", "v = r/ω", "v = ωr²"], dogru: "v = ωr" },
      { soru: "Dönen cisimde doğrusal (tangansiyel) hız nedir?", secenekler: ["v = ωr", "v = ω/r", "v = r/ω", "v = ω²r"], dogru: "v = ωr" },
      { soru: "Dönen cisimde merkezcil (radial) ivme nedir?", secenekler: ["ar = ω²r", "ar = ωr", "ar = v²/r", "ar = v/r"], dogru: "ar = ω²r" },
      { soru: "Dönen cisimde doğrusal (tangansiyel) ivme nedir?", secenekler: ["at = rα", "at = α/r", "at = v²/r", "at = r/v"], dogru: "at = rα" },
      { soru: "Düzlemde dönen cisim yere kaymazsa kritik hız nedir?", secenekler: ["v = √(μgr)", "v = √(gr)", "v = √(g/r)", "v = √(μgr/2)"], dogru: "v = √(μgr)" },
      { soru: "Gezegen hareketlerinin açıklanmasında Newton'un yasaları yeterli midir?", secenekler: ["Hayır, yer çekimi yetersiz", "Evet, tam açıklama sağlar", "Sadece gezegenler için yeterli", "Sadece yıldızlar için yeterli"], dogru: "Hayır, yer çekimi yetersiz" },
      { soru: "Gezegen hareketlerini Newton açıklamak için hangi teori gerekir?", secenekler: ["Genel görelilik", "Özel görelilik", "Kuantum mekaniği", "Termodinamik"], dogru: "Genel görelilik" },
      { soru: "Merkür yüzeyinde yer çekimi acceleration nedir?", secenekler: ["3.7 m/s²", "9.8 m/s²", "1.6 m/s²", "24.8 m/s²"], dogru: "3.7 m/s²" },
      { soru: "Mars yüzeyinde yer çekimi acceleration nedir?", secenekler: ["3.7 m/s²", "9.8 m/s²", "1.6 m/s²", "24.8 m/s²"], dogru: "3.7 m/s²" },
      { soru: "Ay yüzeyinde yer çekimi acceleration nedir?", secenekler: ["1.6 m/s²", "9.8 m/s²", "3.7 m/s²", "24.8 m/s²"], dogru: "1.6 m/s²" },
      { soru: "Jüpiter yüzeyinde yer çekimi acceleration nedir?", secenekler: ["24.8 m/s²", "9.8 m/s²", "3.7 m/s²", "1.6 m/s²"], dogru: "24.8 m/s²" },
      { soru: "Terminal hız nedir?", secenekler: ["Hava sürtünmesi ile ivmenin sıfır olduğu hız", "İvmenin maksimum olduğu hız", "Hızın sabit olduğu hız", "İlk hız"], dogru: "Hava sürtünmesi ile ivmenin sıfır olduğu hız" },
      { soru: "Hava sürtünmesi hangi faktörlere bağlıdır?", secenekler: ["Hız, cisim şekli, yüzey alanı, hava yoğunluğu", "Sadece hıza", "Sadece cisme", "Sadece havaya"], dogru: "Hız, cisim shape, yüzey alanı, hava yoğunluğu" },
      { soru: "Terminal hız formülü yaklaşık nasıl ifade edilir?", secenekler: ["v_terminal ≈ √(2mg/ρAC_d)", "v_terminal ≈ √(mg/ρAC_d)", "v_terminal ≈ √(2mgρA/C_d)", "v_terminal ≈ √(mg/2ρAC_d)"], dogru: "v_terminal ≈ √(2mg/ρAC_d)" },
      { soru: "Paraşüt (paraşüt) nedir?", secenekler: ["Aynı anda düşen iki cismin aynı anda yere çarpması", "Aynı anda yere çarpan iki cisim", "Aynı anda fırlatılan iki cisim", "Eşik koşullarda düşen iki cisim"], dogru: "Aynı anda düşen iki cismin aynı anda yere çarpması" },
      { soru: "Aşağıdakilerden hangisi momentum korunumu örneğidir?", secenekler: ["Top çarpışması", "Serbest düşme", "Sabit ivmeli hareket", "Dairesel hareket"], dogru: "Top çarpışması" },
      { soru: "Görecilik ilkesi neyi ifade eder?", secenekler: ["Eylemsiz referans sisteminde fizik yasaları aynıdır", "Hızlan referans sisteminde fizik yasaları değişir", "Dönen referans sisteminde fizik yasaları değişir", "Yavaşlayan referans sisteminde fizik yasaları değişir"], dogru: "Eylemsiz referans sisteminde fizik yasaları aynıdır" },
      { soru: "Eşitlik ilkesi (Eşdeğerlik ilkesi) neyi ifade eder?", secenekler: ["Yerçekimi kütle eşittir", "Kütle ağırlığa eşittir", "Ağırlık kütleye eşittir", "Eylemsiz sistemde ağırlık sıfırdır"], dogru: "Yerçekimi kütle eşittir" },
      { soru: "İş-enerji eşitliği nedir?", secenekler: ["İş = enerji değişimi", "İş = enerji korunumu", "İş = enerji tükenmesi", "İş = kuvvet × yol"], dogru: "İş = enerji değişimi" },
      { soru: "Potansiyel enerji kinetik enerjiye dönüşebilir mi?", secenekler: ["Evet", "Hayır", "Sadece tersi mümkündür", "Sadece kayıp olabilir"], dogru: "Evet" },
      { soru: "Kinetik enerji potansiyel enerjiye dönüşebilir mi?", secenekler: ["Evet", "Hayır", "Sadece tersi mümkündür", "Sadece kayıp olabilir"], dogru: "Evet" },
      { soru: "Sürtünmesiz kaydırma örneğinde mekanik enerji korunur mu?", secenekler: ["Evet", "Hayır", "Sadece kinetik enerji korunur", "Sadece potansiyel enerji korunur"], dogru: "Evet" },
      { soru: "Elastik çarpışmada mekanik enerji korunur mu?", secenekler: ["Hayır", "Evet", "Sadece kinetik enerji korunur", "Sadece potansiyel enerji korunur"], dogru: "Hayır" },
      { soru: "Elastik çarpışmada kinetik enerji korunur mu?", secenekler: ["Hayır, elastik potansiyel enerjiye dönüşür", "Evet, tam korunur", "Sadece potansiyel enerjiye dönüşür", "İkiye bölünür"], dogru: "Hayır, elastik potansiyel enerjiye dönüşür" },
      { soru: "Atom alt parçacıkları arasındaki kuvvetler hangi temel kuvvetlerdendir?", secenekler: ["Dört temel kuvvet", "Sadece yer çekimi", "Sadece elektromanyetik kuvvet", "Sadece nükleer kuvvet"], dogru: "Dört temel kuvvet" },
      { soru: "Atom çekirde protonlar neden birbirini itmeyerek ayrılmazlar?", secenekler: ["Güçlü nükleer kuvvet", "Elektrik kuvvet", "Manyetik kuvvet", "Yer çekimi"], dogru: "Güçlü nükleer kuvvet" },
      { soru: "Elektron çekirde protonlara neden düşmez?", secenekler: ["Yörünge hareketi nedeniyle", "Elektrik itme", "Manyetik itme", "Yerçekimi az olduğu için"], dogru: "Yörünge hareketi nedeniyle" },
      { soru: "Dört temel kuvvetten en zayıf olanı hangisidir?", secenekler: ["Yer çekimi", "Zayıf nükleer kuvvet", "Elektromanyetik kuvvet", "Güçlü nükleer kuvvet"], dogru: "Yer çekimi" },
      { soru: "Manyetik alanın kaynağı nedir?", secenekler: ["Hareket eden elektrik yükleri", "Kütlesi olan cisimler", "Yüksek sıcaklık", "Yüksek basınç"], dogru: "Hareket eden elektrik yükleri" },
      { soru: "Manyetik alanın birimi nedir?", secenekler: ["Tesla (T)", "Weber (Wb)", "Amper (A)", "Henry (H)"], dogru: "Tesla (T)" },
      { soru: "Manyetik akı birimi nedir?", secenekler: ["Amper (A)", "Tesla (T)", "Weber (Wb)", "Volt (V)"], dogru: "Amper (A)" },
      { soru: "Lorentz kuvveti nedir?", secenekler: ["Manyetik alandaki hareketli yüke etkileyen kuvvet", "Elektrik alandaki hareketli yüke etkileyen kuvvet", "Yerçekimi kuvveti", "Sürtünme kuvveti"], dogru: "Manyetik alandaki hareketli yüke etkileyen kuvvet" },
      { soru: "Lorentz kuvveti yönü nasıldır?", secenekler: ["Hıza, manyetik alanına dik", "Hızla aynı yönde", "Manyetik alanına paralel", "Hız zıt yönde"], dogru: "Hıza, manyetik alanına dik" },
      { soru: "Elektrik motoru hangi prensiple çalışır?", secenekler: ["Lorentz kuvveti", "Newton'un hareket yasaları", "Termodinamik yasaları", "Optik yasaları"], dogru: "Lorentz kuvveti" },
      { soru: "Jeneratör hangi prensiple çalışır?", secenekler: ["Elektromanyetik indüksiyon", "Lorentz kuvveti", "Newton'un hareket yasaları", "Termodinamik yasaları"], dogru: "Elektromanyetik indüksiyon" },
      { soru: "Transformatör hangi prensiple çalışır?", secenekler: ["Elektromanyetik indüksiyon", "Lorentz kuvveti", "Newton'un hareket yasaları", "Termodinamik yasaları"], dogru: "Elektromanyetik indüksiyon" },
      { soru: "Mikroskop nasıl görüntü oluşturur?", secenekler: ["Elektron demetleri", "Fotonlar", "Protonlar", "Nötronlar"], dogru: "Elektron demetleri" },
      { soru: "Elektron mikroskobu ile optik mikroskop arasındaki temel fark nedir?", secenekler: ["Elektron demetleri kullanır", "Fotonlar kullanır", "Canlı örnek gerektirir", "Sadece cansız örnek görüntüler"], dogru: "Elektron demetleri kullanır" },
      { soru: "Tarama electron mikroskobu (SEM) nedir?", secenekler: ["Elektron demetleri ile yüzey taraması", "Fotonlar ile yüzey taraması", "Manyetik alan ile yüzey taraması", "Ses dalgaları ile yüzey taraması"], dogru: "Elektron demetleri ile yüzey taraması" },
      { soru: "Atomik kuvvet mikroskobu (AFM) nedir?", secenekler: ["Tarama probu ile yüzey taraması", "Elektron demetleri ile yüzey taraması", "Fotonlar ile yüzey taraması", "Manyetik alan ile yüzey taraması"], dogru: "Tarama probu ile yüzey taraması" },
      { soru: "Nanoteknoloji fizikte hangi alanda kullanılır?", secenekler: ["Malzeme bilimi, tıp, elektronik", "Sadece astronomide", "Sadece biyolojide", "Sadece kimyada"], dogru: "Malzeme bilimi, tıp, elektronik" },
      { soru: "Kuantum noktaları nedir?", secenekler: ["0 boyutlu yapılar", "1 boyutlu yapılar", "2 boyutlu yapılar", "3 boyutlu yapılar"], dogru: "0 boyutlu yapılar" },
      {u: "Kuantum telleri nedir?", secenekler: ["1 boyutlu yapılar", "0 boyutlu yapılar", "2 boyutlu yapılar", "3 boyutlu yapılar"], dogru: "1 boyutlu yapılar" },
      { soru: "Kuantum kuyuları nedir?", secenekler: ["0 boyutlu yapılar", "1 boyutlu yapılar", "2 boyutlu yapılar", "3 boyutlu yapılar"], dogru: "0 boyutlu yapılar" },
      { soru: "Graphene nedir?", secenekler: ["Tek katman karbon atomları", "İki katman karbon atomları", "Üç katman karbon atomları", "Çok katman karbon atomları"], dogru: "Tek katman karbon atomları" }
    ]}
  ]
}
